import style from '../style.module.css'

export const metadata = {
    title: "Entertainment",
    description: "Generated by create next app",
};

export default function Places() {
    return (
        <div className={style.main_container}>
            <div className={style.chiled_container}>
                Places
            </div>
        </div>
    )
}