import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "./provaider";
import Footer from "@/components/Footer/Footer";
import Navigation from "@/components/Navigation/Navigation";
import Menu from "@/components/Menu/Menu";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">


      <body className={inter.className}>
        <StoreProvider>
          <header>
            <Navigation />
          </header>
      
            <Menu />
          {children}

          <footer>
            <Footer />
          </footer>
        </StoreProvider>
      </body>

    </html>
  );
}
